---
esphome:
  name: test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: wifi_ssid
  password: wifi_password
  fast_connect: true

logger:

external_components:
  - source: components

esp32_ble_tracker:

ble_client:
  - mac_address: "00:00:00:00:00:00"
    id: idasen_desk

idasen_desk_controller:
  ble_client_id: idasen_desk

cover:
  - platform: idasen_desk_controller
    name: "Desk"
