---
esphome:
  name: test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: wifi_ssid
  password: wifi_password
  fast_connect: true

logger:

external_components:
  - source: components

idasen_desk_controller:
  mac_address: "00:00:00:00:00:00"

sensor:
  - platform: idasen_desk_controller
    desk_height:
      name: "Desk Height"

binary_sensor:
  - platform: idasen_desk_controller
    name: "Desk Connection"
    type: CONNECTION
  - platform: idasen_desk_controller
    name: "Desk Moving"
    type: MOVING

cover:
  - platform: idasen_desk_controller
    name: "Desk"
